// node ./tools/o3dlod.js <in.o3d> <in_facecolors.bin> <anim.bin> <anim.json> \
//                        <target_triangles> <out.o3d> <out_facecolors.bin> <out.inc>
//
// Offline mesh LOD for the T-Rex renderer (OPTIMIZATION.md section 10 item 10).
//
// Decimates the O3D polygon list by greedy half-edge collapse onto EXISTING
// vertices only: the extracted PS1 morph animation addresses vertices by
// their TMD index (base pose, 46 gait poses, sparse targets 4-8), so no new
// vertex position may ever be invented and the TMD/TANM files stay
// byte-identical.  Only the O3D changes, and with it the two per-triangle
// sidecars (face colours are inherited here, face normals are regenerated by
// o3d2facenormals.js from the decimated O3D).
//
// Constraints per candidate collapse (b folds onto a):
//  - vertices of untextured polygons (the PS1 eyes) are untouchable,
//  - every retargeted triangle must keep its winding (no normal flip: the
//    negative-area front-face rule would otherwise cull it),
//  - b's corner UV in a retargeted triangle is replaced by a's UV taken from
//    a triangle of the SAME texture page, preferring one that shares another
//    vertex; no such donor means the collapse is rejected (seam guard),
//  - boundary vertices only collapse along boundary edges,
//  - morph-active vertices (TANM sparse targets 4-8, big-endian s16 deltas
//    weighted by each target's peak Q12 autoplay weight) pay a cost premium
//    so the animated face and jaw keep their triangle density.
//
// With target == input count the tool performs zero collapses and writes a
// byte-identical O3D (back/front BSP words are passed through unused), which
// is the self-test the Makefile can pin.

const fs = require("fs");

if (process.argv.length < 12) {
    console.error("usage: o3dlod.js in.o3d in_facecolors.bin in_cornernormals.bin " +
        "anim.bin anim.json target_triangles out.o3d out_facecolors.bin " +
        "out_cornernormals.bin out.inc");
    process.exit(1);
}

const [inO3dPath, inColorsPath, inNormalsPath, animBinPath, animJsonPath,
    targetArg, outO3dPath, outColorsPath, outNormalsPath, outIncPath] = process.argv.slice(2);
const targetTriangles = parseInt(targetArg);

const o3d = fs.readFileSync(inO3dPath);
const faceColors = fs.readFileSync(inColorsPath);
const cornerNormals = fs.readFileSync(inNormalsPath);
const animBin = fs.readFileSync(animBinPath);
const animJson = JSON.parse(fs.readFileSync(animJsonPath, "utf-8"));

// ---------------------------------------------------------------- O3D parse
const HEADER_BYTES = 24;           // 3 count words + 3 words + 3 longs
const POINT_BYTES = 12;
const NORMAL_BYTES = 12;
const POLY_WORDS = 16;             // 3-point polygons only, checked below

const pointCount = o3d.readUInt16BE(0);
const normalCount = o3d.readUInt16BE(2);
const polyCount = o3d.readUInt16BE(4);
const polyOffset = HEADER_BYTES + pointCount * POINT_BYTES + normalCount * NORMAL_BYTES;

if (faceColors.length !== polyCount * 4) {
    console.error(`facecolors: ${faceColors.length} bytes, expected ${polyCount * 4}`);
    process.exit(1);
}
if (cornerNormals.length !== polyCount * 6) {
    console.error(`cornernormals: ${cornerNormals.length} bytes, expected ${polyCount * 6}`);
    process.exit(1);
}

const points = [];
for (let i = 0; i < pointCount; i++) {
    const off = HEADER_BYTES + i * POINT_BYTES;
    points.push({
        x: o3d.readInt32BE(off),
        y: o3d.readInt32BE(off + 4),
        z: o3d.readInt32BE(off + 8)
    });
}

const polys = [];
for (let i = 0; i < polyCount; i++) {
    const off = polyOffset + i * POLY_WORDS * 2;
    const words = [];
    for (let w = 0; w < POLY_WORDS; w++) {
        words.push(o3d.readUInt16BE(off + w * 2));
    }
    if (words[0] !== 3) {
        console.error(`polygon ${i}: point count ${words[0]}, only triangles supported`);
        process.exit(1);
    }
    polys.push({
        words: words,
        idx: [words[5] / 3, words[6] / 3, words[7] / 3],
        uv: [[words[8], words[9]], [words[10], words[11]], [words[12], words[13]]],
        nrm: [cornerNormals.readUInt16BE(i * 6), cornerNormals.readUInt16BE(i * 6 + 2),
            cornerNormals.readUInt16BE(i * 6 + 4)],
        clut: words[14],
        tpage: words[15],
        textured: words[15] !== 0,
        alive: true
    });
}

// -------------------------------------------------- morph protection weights
// Sparse targets 4-8: dense s16 x/y/z windows starting at start_vertex.
// Weight = peak |delta| scaled by the target's peak autoplay Q12 weight
// (target 4, the jaw, never plays in autoplay but is driven by the Falcon's
// vocalisation envelope at up to 4096, so it protects at full scale).
const morphWeight = new Float64Array(pointCount);
for (const t of animJson.targets) {
    if (t.index < 4) continue;                    // gait targets cover everything
    const peakQ12 = t.index === 4 ? 4096 :
        Math.max(Math.abs(t.autoplay.minimum_weight), Math.abs(t.autoplay.maximum_weight));
    if (peakQ12 === 0) continue;
    const scale = peakQ12 / 4096;
    for (let v = 0; v < t.vertex_count; v++) {
        const off = t.binary_delta_offset + v * 6;
        const dx = animBin.readInt16BE(off);
        const dy = animBin.readInt16BE(off + 2);
        const dz = animBin.readInt16BE(off + 4);
        const mag = Math.max(Math.abs(dx), Math.abs(dy), Math.abs(dz)) * scale;
        const vi = t.start_vertex + v;
        if (mag > morphWeight[vi]) morphWeight[vi] = mag;
    }
}
let morphMax = 0;
for (let v = 0; v < pointCount; v++) if (morphWeight[v] > morphMax) morphMax = morphWeight[v];
if (morphMax > 0) for (let v = 0; v < pointCount; v++) morphWeight[v] /= morphMax;

// ------------------------------------------------------- adjacency and edges
const vertFaces = Array.from({ length: pointCount }, () => new Set());
polys.forEach((p, pi) => p.idx.forEach(v => vertFaces[v].add(pi)));

const locked = new Uint8Array(pointCount);        // untextured-polygon vertices
polys.forEach(p => { if (!p.textured) p.idx.forEach(v => { locked[v] = 1; }); });

// Free-standing mini features: the PS1 teeth (and similar flags) are tiny
// connected components of their own.  Curvature saliency cannot see them --
// an isolated fan's normals all agree -- and their quadrics are tiny, so
// they are the cheapest collapses of the whole mesh and vanish first.
// Lock every vertex of any edge-connected component at or below
// SMALL_COMPONENT triangles.
const SMALL_COMPONENT = 8;
{
    const comp = new Int32Array(polys.length).fill(-1);
    let comps = 0;
    const edgeMap = new Map();
    polys.forEach((p, pi) => {
        for (let e = 0; e < 3; e++) {
            const k = edgeKey(p.idx[e], p.idx[(e + 1) % 3]);
            if (!edgeMap.has(k)) edgeMap.set(k, []);
            edgeMap.get(k).push(pi);
        }
    });
    for (let seed = 0; seed < polys.length; seed++) {
        if (comp[seed] >= 0) continue;
        const stack = [seed];
        comp[seed] = comps;
        const members = [];
        while (stack.length) {
            const pi = stack.pop();
            members.push(pi);
            const p = polys[pi];
            for (let e = 0; e < 3; e++) {
                const k = edgeKey(p.idx[e], p.idx[(e + 1) % 3]);
                for (const qi of edgeMap.get(k)) {
                    if (comp[qi] < 0) { comp[qi] = comps; stack.push(qi); }
                }
            }
        }
        if (members.length <= SMALL_COMPONENT) {
            for (const pi of members) polys[pi].idx.forEach(v => { locked[v] = 1; });
        }
        comps++;
    }
    const lockedTris = polys.filter(p => p.idx.some(v => locked[v])).length;
    console.log(`o3dlod: ${comps} components, ` +
        `${lockedTris} triangles touch locked vertices`);
}

// The mouth is THE animated feature of this scene: the jaw (target 4, driven
// by the Falcon's vocalisation envelope) and the lip target 5 move exactly
// these vertices, and the teeth ride on them.  A cost premium proved too
// soft -- the tooth band and the lip line still collapsed away -- so every
// vertex with a nonzero T4/T5 delta is locked outright and the triangle
// budget comes from the rest of the body.
const MOUTH_LOCK_TARGETS = [4, 5];
const MOUTH_LOCK_RINGS = 1;
{
    const mouth = new Uint8Array(pointCount);
    for (const t of animJson.targets) {
        if (!MOUTH_LOCK_TARGETS.includes(t.index)) continue;
        for (let v = 0; v < t.vertex_count; v++) {
            const off = t.binary_delta_offset + v * 6;
            if (animBin.readInt16BE(off) || animBin.readInt16BE(off + 2) ||
                animBin.readInt16BE(off + 4)) {
                mouth[t.start_vertex + v] = 1;
            }
        }
    }
    // Dilate the lock by triangle adjacency: the UPPER teeth ride the skull,
    // not the jaw, so they carry no T4/T5 delta -- but they share triangles
    // with the locked lip line.  One ring pulls them (and the gum line they
    // stand on) into the lock without touching the eye lock's surroundings.
    for (let ring = 0; ring < MOUTH_LOCK_RINGS; ring++) {
        const grow = [];
        for (const p of polys) {
            if (p.idx.some(v => mouth[v])) {
                for (const v of p.idx) if (!mouth[v]) grow.push(v);
            }
        }
        for (const v of grow) mouth[v] = 1;
    }
    let mouthLocked = 0;
    for (let v = 0; v < pointCount; v++) {
        if (mouth[v] && !locked[v]) { locked[v] = 1; mouthLocked++; }
    }
    console.log(`o3dlod: ${mouthLocked} mouth vertices locked ` +
        `(targets 4+5 plus ${MOUTH_LOCK_RINGS} adjacency ring)`);
}

function edgeKey(a, b) { return a < b ? a * 65536 + b : b * 65536 + a; }

function edgeFaceCount(a, b) {
    let n = 0;
    for (const pi of vertFaces[a]) {
        if (polys[pi].alive && polys[pi].idx.includes(b)) n++;
    }
    return n;
}

const boundaryVertex = new Uint8Array(pointCount);
function refreshBoundary(v) {
    boundaryVertex[v] = 0;
    const counts = new Map();
    for (const pi of vertFaces[v]) {
        if (!polys[pi].alive) continue;
        for (const w of polys[pi].idx) {
            if (w === v) continue;
            counts.set(w, (counts.get(w) || 0) + 1);
        }
    }
    for (const c of counts.values()) {
        if (c === 1) { boundaryVertex[v] = 1; return; }
    }
}
for (let v = 0; v < pointCount; v++) refreshBoundary(v);

function faceNormal(i0, i1, i2) {
    const p0 = points[i0], p1 = points[i1], p2 = points[i2];
    const ax = p1.x - p0.x, ay = p1.y - p0.y, az = p1.z - p0.z;
    const bx = p2.x - p0.x, by = p2.y - p0.y, bz = p2.z - p0.z;
    return { x: ay * bz - az * by, y: az * bx - ax * bz, z: ax * by - ay * bx };
}

function dot(n, m) { return n.x * m.x + n.y * m.y + n.z * m.z; }

function dist2(a, b) {
    const dx = points[a].x - points[b].x;
    const dy = points[a].y - points[b].y;
    const dz = points[a].z - points[b].z;
    return dx * dx + dy * dy + dz * dz;
}

// UV donor: a's corner UV from a live triangle of the requested page,
// preferring one that also references `prefer`.  refUV is the corner UV
// being replaced: a donor further than MAX_UV_DRIFT texels (Manhattan) from
// it belongs to a different part of the atlas -- crossing over would smear
// foreign texture across the retargeted triangle (this is what erased the
// teeth: mouth-interior donors replaced the tooth band), so such donors are
// rejected and with them the collapse.
// Corner-normal donor: a's TMD normal index from a live triangle that
// references a, preferring one that also shares `prefer` so smoothing
// groups stay together across hard edges (the eye rims).  Normals are bound
// to the vertex position, so unlike UVs no page or drift constraint applies
// and a donor always exists while a is alive.
function normalDonor(a, prefer) {
    let fallback = -1;
    for (const pi of vertFaces[a]) {
        const p = polys[pi];
        if (!p.alive) continue;
        const corner = p.idx.indexOf(a);
        if (corner < 0) continue;
        if (prefer >= 0 && p.idx.includes(prefer)) return p.nrm[corner];
        if (fallback < 0) fallback = p.nrm[corner];
    }
    return fallback;
}

const MAX_UV_DRIFT = 40;
function uvDonor(a, tpage, prefer, refUV) {
    let fallback = null;
    for (const pi of vertFaces[a]) {
        const p = polys[pi];
        if (!p.alive || p.tpage !== tpage) continue;
        const corner = p.idx.indexOf(a);
        if (corner < 0) continue;
        const uv = p.uv[corner];
        if (Math.abs(uv[0] - refUV[0]) + Math.abs(uv[1] - refUV[1]) > MAX_UV_DRIFT) continue;
        if (prefer >= 0 && p.idx.includes(prefer)) return uv;
        if (!fallback) fallback = uv;
    }
    return fallback;
}

const MORPH_PREMIUM = 24;          // cost multiplier at full morph activity
const BEND_PREMIUM = 6;            // cost multiplier at 90-degree normal bend
const BOUNDARY_WEIGHT = 4;         // quadric weight of open-edge constraints
const SALIENCY_PREMIUM = 25;       // cost multiplier at maximum curvature
const HEAD_PREMIUM = 6;            // cost multiplier inside the head sphere
const HEAD_RADIUS_SCALE = 2.2;     // sphere radius over the morph spread
const DETAIL_PREMIUM = 8;          // cost multiplier at the finest source detail
const DETAIL_CAP = 16;             // area ratio that counts as full detail
const ABSORB_PENALTY = 0.5;        // cost growth per collapse a vertex absorbed

// Cascade brake: without it the greedy loop strip-mines whatever region the
// locks and premiums leave cheap -- the tail collapsed to a stump with its
// spike-locked tip floating detached, and the legs tore open.  Every
// absorbed collapse makes the next one at that vertex more expensive, so
// decimation spreads across the body instead of hollowing one limb.
const absorbed = new Float64Array(pointCount);

// Artist-intent detail weight: the source mesh concentrates small triangles
// exactly where detail matters -- teeth, claws, eye rims -- and QEM alone
// underprices them because small triangles make small quadrics.  Weight
// each vertex by how much smaller its smallest ORIGINAL triangle is than
// the median triangle, on a log scale capped at DETAIL_CAP.
const detailWeight = new Float64Array(pointCount);
{
    const areas = [];
    const minArea = new Float64Array(pointCount).fill(Infinity);
    for (const p of polys) {
        const n = faceNormal(p.idx[0], p.idx[1], p.idx[2]);
        const area = Math.sqrt(dot(n, n)) / 2;
        if (area === 0) continue;
        areas.push(area);
        for (const v of p.idx) if (area < minArea[v]) minArea[v] = area;
    }
    areas.sort((x, y) => x - y);
    const median = areas[areas.length >> 1] || 1;
    const logCap = Math.log(DETAIL_CAP);
    for (let v = 0; v < pointCount; v++) {
        if (!isFinite(minArea[v]) || minArea[v] >= median) continue;
        detailWeight[v] = Math.min(1, Math.log(median / minArea[v]) / logCap);
    }
}

// Head density preference: the camera spends the close-ups on the head, and
// eye sockets or brow ridges deform visibly at a budget the body absorbs
// without notice.  The head is located from the data instead of an axis
// guess: the centroid of every vertex the mouth and brow morph targets
// (4, 5, 7) move, with the sphere radius scaled from their RMS spread.
// Inside, collapses pay a premium -- a preference, not a lock, so the
// triangle budget stays reachable and the body pays the difference.
const headWeight = new Uint8Array(pointCount);
{
    let cx = 0, cy = 0, cz = 0, n = 0;
    const members = [];
    for (const t of animJson.targets) {
        if (![4, 5, 7].includes(t.index)) continue;
        for (let v = 0; v < t.vertex_count; v++) {
            const off = t.binary_delta_offset + v * 6;
            if (animBin.readInt16BE(off) || animBin.readInt16BE(off + 2) ||
                animBin.readInt16BE(off + 4)) {
                const vi = t.start_vertex + v;
                members.push(vi);
                cx += points[vi].x; cy += points[vi].y; cz += points[vi].z;
                n++;
            }
        }
    }
    if (n > 0) {
        cx /= n; cy /= n; cz /= n;
        let rms = 0;
        for (const vi of members) {
            const dx = points[vi].x - cx, dy = points[vi].y - cy, dz = points[vi].z - cz;
            rms += dx * dx + dy * dy + dz * dz;
        }
        const r2 = HEAD_RADIUS_SCALE * HEAD_RADIUS_SCALE * (rms / n);
        let inside = 0;
        for (let v = 0; v < pointCount; v++) {
            const dx = points[v].x - cx, dy = points[v].y - cy, dz = points[v].z - cz;
            if (dx * dx + dy * dy + dz * dz <= r2) { headWeight[v] = 1; inside++; }
        }
        console.log(`o3dlod: head sphere covers ${inside} vertices`);
    }
}

// Static curvature saliency from the ORIGINAL mesh: 1 minus the length of
// the area-weighted normal sum over the length sum.  Flat regions score ~0,
// spikes and ridges -- the teeth, the claws -- score towards 1.  QEM alone
// underprotects such features at a 70% budget cut because their triangles
// are tiny; this term makes their collapses expensive regardless of size.
const saliency = new Float64Array(pointCount);
{
    const sumX = new Float64Array(pointCount);
    const sumY = new Float64Array(pointCount);
    const sumZ = new Float64Array(pointCount);
    const sumLen = new Float64Array(pointCount);
    for (const p of polys) {
        const n = faceNormal(p.idx[0], p.idx[1], p.idx[2]);
        const len = Math.sqrt(dot(n, n));
        if (len === 0) continue;
        for (const v of p.idx) {
            sumX[v] += n.x; sumY[v] += n.y; sumZ[v] += n.z;
            sumLen[v] += len;
        }
    }
    for (let v = 0; v < pointCount; v++) {
        if (sumLen[v] === 0) continue;
        const l = Math.sqrt(sumX[v] ** 2 + sumY[v] ** 2 + sumZ[v] ** 2);
        saliency[v] = 1 - l / sumLen[v];
    }
}

// Spike lock: curvature this extreme only occurs at free-standing tips --
// tooth points, claw tips, the features a viewer names first when they go
// missing.  Every soft premium still lost the claws, so tips lock outright,
// and a few adjacency rings grow the lock down the thin digits they sit on
// (a finger's shaft scores only middling saliency and collapsed away even
// with its tip pinned).  Tooth-spike rings just re-lock mouth vertices.
const SPIKE_LOCK_SALIENCY = 0.55;
const SPIKE_LOCK_RINGS = 3;
const SPIKE_RING_SALIENCY = 0.22;  // rings only follow curved shafts
{
    const spike = new Uint8Array(pointCount);
    let tips = 0;
    // Only tips that are not already locked seed a ring: the tooth spikes
    // are covered by the mouth lock, and growing rings from them would
    // needlessly freeze face area around the lip line.
    for (let v = 0; v < pointCount; v++) {
        if (saliency[v] >= SPIKE_LOCK_SALIENCY && !locked[v]) { spike[v] = 1; tips++; }
    }
    // Triangle dilation grows exponentially into flat surroundings, so the
    // rings only claim vertices that are themselves curved -- a digit's
    // shaft scores middling saliency from its tube bend, the palm and the
    // chest behind it do not.
    for (let ring = 0; ring < SPIKE_LOCK_RINGS; ring++) {
        const grow = [];
        for (const p of polys) {
            if (p.idx.some(v => spike[v])) {
                for (const v of p.idx) {
                    if (!spike[v] && saliency[v] >= SPIKE_RING_SALIENCY) grow.push(v);
                }
            }
        }
        for (const v of grow) spike[v] = 1;
    }
    let n = 0;
    for (let v = 0; v < pointCount; v++) {
        if (spike[v] && !locked[v]) { locked[v] = 1; n++; }
    }
    console.log(`o3dlod: ${tips} spike tips, ${n} vertices locked with ` +
        `${SPIKE_LOCK_RINGS} rings`);
}

// Quadric error metrics (Garland/Heckbert), area-weighted, on the 4x4
// symmetric plane-quadric per vertex.  Half-edge collapse b->a is charged
// the accumulated quadric of BOTH endpoints evaluated at a's position, and
// a absorbs b's quadric afterwards -- shrinking the same feature repeatedly
// gets progressively more expensive, which is exactly what a plain
// edge-length metric lacks (it eats small-triangle features like the arms
// and toes first).
const quadric = Array.from({ length: pointCount }, () => new Float64Array(10));

function addPlaneQuadric(q, nx, ny, nz, d, w) {
    q[0] += w * nx * nx; q[1] += w * nx * ny; q[2] += w * nx * nz; q[3] += w * nx * d;
    q[4] += w * ny * ny; q[5] += w * ny * nz; q[6] += w * ny * d;
    q[7] += w * nz * nz; q[8] += w * nz * d;
    q[9] += w * d * d;
}

function quadricError(q, p) {
    const { x, y, z } = p;
    return q[0] * x * x + 2 * q[1] * x * y + 2 * q[2] * x * z + 2 * q[3] * x +
           q[4] * y * y + 2 * q[5] * y * z + 2 * q[6] * y +
           q[7] * z * z + 2 * q[8] * z + q[9];
}

for (const p of polys) {
    const n = faceNormal(p.idx[0], p.idx[1], p.idx[2]);
    const area = Math.sqrt(dot(n, n)) / 2;
    if (area === 0) continue;
    const inv = 1 / (2 * area);
    const nx = n.x * inv, ny = n.y * inv, nz = n.z * inv;
    const p0 = points[p.idx[0]];
    const d = -(nx * p0.x + ny * p0.y + nz * p0.z);
    for (const v of p.idx) addPlaneQuadric(quadric[v], nx, ny, nz, d, area);
}

// Open-edge constraint planes: perpendicular to the face through the edge,
// so boundaries (the soles, any open rims) resist being pulled inward.
for (const p of polys) {
    for (let e = 0; e < 3; e++) {
        const a = p.idx[e], b = p.idx[(e + 1) % 3];
        if (edgeFaceCount(a, b) !== 1) continue;
        const fn = faceNormal(p.idx[0], p.idx[1], p.idx[2]);
        const ex = points[b].x - points[a].x;
        const ey = points[b].y - points[a].y;
        const ez = points[b].z - points[a].z;
        let cx = ey * fn.z - ez * fn.y;
        let cy = ez * fn.x - ex * fn.z;
        let cz = ex * fn.y - ey * fn.x;
        const cl = Math.sqrt(cx * cx + cy * cy + cz * cz);
        if (cl === 0) continue;
        cx /= cl; cy /= cl; cz /= cl;
        const d = -(cx * points[a].x + cy * points[a].y + cz * points[a].z);
        const w = BOUNDARY_WEIGHT * (ex * ex + ey * ey + ez * ez);
        addPlaneQuadric(quadric[a], cx, cy, cz, d, w);
        addPlaneQuadric(quadric[b], cx, cy, cz, d, w);
    }
}

const rejects = { locked: 0, boundary: 0, flip: 0, uv: 0 };

// Evaluate collapse b->a.  Returns {cost, retargets:[{pi, corner, uv}]} or null.
function evaluateCollapse(b, a) {
    if (a === b || locked[a] || locked[b]) { rejects.locked++; return null; }
    const edgeFaces = edgeFaceCount(a, b);
    if (edgeFaces === 0) return null;
    if (boundaryVertex[b] && edgeFaces !== 1) { rejects.boundary++; return null; }
    // boundary vertex, interior edge: pulling it inward tears the silhouette

    let worstBend = 0;
    const retargets = [];
    for (const pi of vertFaces[b]) {
        const p = polys[pi];
        if (!p.alive) continue;
        if (p.idx.includes(a)) continue;                     // shared face dies
        const corner = p.idx.indexOf(b);
        const ni = p.idx.slice();
        ni[corner] = a;
        const before = faceNormal(p.idx[0], p.idx[1], p.idx[2]);
        const after = faceNormal(ni[0], ni[1], ni[2]);
        const d = dot(before, after);
        if (d <= 0) { rejects.flip++; return null; }         // winding flip
        const lb = Math.sqrt(dot(before, before)), la = Math.sqrt(dot(after, after));
        if (lb > 0 && la > 0) {
            const bend = 1 - d / (lb * la);
            if (bend > worstBend) worstBend = bend;
        }
        let uv = null;
        if (p.textured) {
            const refUV = p.uv[corner];
            uv = uvDonor(a, p.tpage, p.idx[(corner + 1) % 3], refUV) ||
                 uvDonor(a, p.tpage, p.idx[(corner + 2) % 3], refUV) ||
                 uvDonor(a, p.tpage, -1, refUV);
            if (!uv) { rejects.uv++; return null; }  // no donor in drift range
        }
        let nrm = normalDonor(a, p.idx[(corner + 1) % 3]);
        if (nrm < 0) nrm = normalDonor(a, -1);
        retargets.push({ pi, corner, uv, nrm });
    }

    const qsum = new Float64Array(10);
    for (let i = 0; i < 10; i++) qsum[i] = quadric[a][i] + quadric[b][i];
    const qerr = Math.max(0, quadricError(qsum, points[a]));
    const cost = (qerr + 1e-3 * dist2(a, b)) *
        (1 + MORPH_PREMIUM * morphWeight[b] + MORPH_PREMIUM * 0.5 * morphWeight[a]) *
        (1 + SALIENCY_PREMIUM * Math.max(saliency[a], saliency[b])) *
        (1 + HEAD_PREMIUM * Math.max(headWeight[a], headWeight[b])) *
        (1 + DETAIL_PREMIUM * Math.max(detailWeight[a], detailWeight[b])) *
        (1 + absorbed[a] + absorbed[b]) *
        (1 + BEND_PREMIUM * worstBend);
    return { cost, retargets };
}

function applyCollapse(b, a, retargets) {
    for (const pi of vertFaces[b]) {
        const p = polys[pi];
        if (p.alive && p.idx.includes(a)) p.alive = false;   // shared faces die
    }
    for (const r of retargets) {
        const p = polys[r.pi];
        if (!p.alive) continue;
        p.idx[r.corner] = a;
        p.words[5 + r.corner] = a * 3;
        if (r.uv) {
            p.uv[r.corner] = r.uv;
            p.words[8 + r.corner * 2] = r.uv[0];
            p.words[9 + r.corner * 2] = r.uv[1];
        }
        if (r.nrm >= 0) p.nrm[r.corner] = r.nrm;
        vertFaces[a].add(r.pi);
    }
    vertFaces[b].clear();
    for (let i = 0; i < 10; i++) quadric[a][i] += quadric[b][i];
    absorbed[a] += ABSORB_PENALTY + absorbed[b];
    refreshBoundary(a);
    const touched = new Set();
    for (const pi of vertFaces[a]) {
        if (polys[pi].alive) polys[pi].idx.forEach(v => touched.add(v));
    }
    for (const v of touched) refreshBoundary(v);
}

// ------------------------------------------------------------- greedy loop
let alive = polys.filter(p => p.alive).length;
const startAlive = alive;
let collapses = 0;
let rejected = 0;

while (alive > targetTriangles) {
    // Rebuild the candidate list over live edges.  O(edges) per collapse is
    // fine for an offline tool at this mesh size.
    let best = null;
    const seen = new Set();
    for (let pi = 0; pi < polys.length; pi++) {
        const p = polys[pi];
        if (!p.alive) continue;
        for (let e = 0; e < 3; e++) {
            const a = p.idx[e], b = p.idx[(e + 1) % 3];
            const key = edgeKey(a, b);
            if (seen.has(key)) continue;
            seen.add(key);
            for (const [from, to] of [[b, a], [a, b]]) {
                const r = evaluateCollapse(from, to);
                if (r && (!best || r.cost < best.cost)) {
                    best = { from, to, ...r };
                }
            }
        }
    }
    if (!best) {
        console.error(`no legal collapse left at ${alive} triangles ` +
            `(target ${targetTriangles}); writing what was reached`);
        console.error(`final-scan rejects: ${JSON.stringify(rejects)}`);
        break;
    }
    rejects.locked = rejects.boundary = rejects.flip = rejects.uv = 0;
    applyCollapse(best.from, best.to, best.retargets);
    collapses++;
    alive = polys.filter(p => p.alive).length;
}

// ------------------------------------------------------------------ output
const survivors = polys.map((p, pi) => ({ p, pi })).filter(e => e.p.alive);
const outSize = polyOffset + survivors.length * POLY_WORDS * 2;
const out = Buffer.alloc(outSize);
o3d.copy(out, 0, 0, polyOffset);                  // header + points + normals
out.writeUInt16BE(survivors.length, 4);           // polygon count

let off = polyOffset;
for (const e of survivors) {
    for (const w of e.p.words) {
        out.writeUInt16BE(w, off);
        off += 2;
    }
}
fs.writeFileSync(outO3dPath, out);

const outColors = Buffer.alloc(survivors.length * 4);
survivors.forEach((e, i) => faceColors.copy(outColors, i * 4, e.pi * 4, e.pi * 4 + 4));
fs.writeFileSync(outColorsPath, outColors);

const outNormals = Buffer.alloc(survivors.length * 6);
const lodReferenced = new Set();
survivors.forEach((e, i) => {
    e.p.nrm.forEach((n, corner) => {
        outNormals.writeUInt16BE(n, i * 6 + corner * 2);
        lodReferenced.add(n);
    });
});
fs.writeFileSync(outNormalsPath, outNormals);

fs.writeFileSync(outIncPath,
    `; generated by tools/o3dlod.js -- triangle count of ${outO3dPath}\n` +
    `TREX_PRIMITIVES\t\t= ${survivors.length}\n`);

const untextured = survivors.filter(e => !e.p.textured).length;
console.log(`o3dlod: ${startAlive} -> ${survivors.length} triangles ` +
    `(${collapses} collapses), ${untextured} untextured kept, ` +
    `${pointCount} vertices untouched, ` +
    `${lodReferenced.size} corner normals referenced`);
